### ISSUE TITLE
Polyfish

### ISSUE THREAD

**Issue by spanishmonk** [khalid-a-omar/Polyfish#6]
I have not been able to install into Fritz or Hiarcs, the engine name is not Polyfish but Stockfish when you try to add the engine, I have had no problems installing previous Polyfish in the past.

**Comment by khalid-a-omar** [comment]
My bad :(

The build I published was indeed identical to Stockfish Dev because I forgot to turn on one flag in the Makefile which will tell the compiler to build Polyfish code instead of/in addition to SF

Thank you for the flag. I have deleted the faulty release, and will publish a new one soon.

**Comment by khalid-a-omar** [comment]
I have released [20220603](https://github.com/khalid-a-omar/Polyfish/releases/tag/20220603) today which fixes the problem you mentioned. Thank you.
