### ISSUE TITLE
Optimization to different book formats

### ISSUE THREAD

**Issue by Frosty54** [khalid-a-omar/Polyfish#7]
Is it possible support other formats of books except bin ctg?

**Comment by khalid-a-omar** [comment]
I don't think I will be adding more book formats to Polyfish anytime soon. I believe CTG and BIN are the most common formats used by the communities I'm involved in and therefore I decided to add them.

I haven't invested time to look into other formats so I don't know if they are complex or not, but in theory adding more book formats is possible. It is a matter of writing the code.
