### ISSUE TITLE
Missing compiles for Polyfish 20231107

### ISSUE THREAD

**Issue by tonymokonen** [khalid-a-omar/Polyfish#9]
There are dead links for some of the compiles of the latest version of Polyfish.  Missing are:

Windows_Polyfish_231107_x86-64-avx512.zip
Linux_Polyfish_231107_x86-64-vnni256.zip
Linux_Polyfish_231107_x86-64-avx512.zip
Linux_Polyfish_231107_x86-64-bmi2.zip
Linux_Polyfish_231107_x86-64-avx2.zip

**Comment by khalid-a-omar** [comment]
Sorry, my bad!
I have uploaded the files again and double checked the links. Thank you for reporting the problem.
